{
 "title": "NetApp",
 "time": { "from": "2018-10-04T20:21:54.146Z", "to": "2018-10-04T21:08:02.110Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "LIF",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "svm" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lif",
     "select": [
      [
       { "params": [ "recv_data" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "svm" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lif",
     "select": [
      [
       { "params": [ "sent_data" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processor",
     "select": [
      [
       { "params": [ "avg_processor_busy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processor",
     "select": [
      [
       { "params": [ "domain_busy.network" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ethernet Port",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eth_port",
     "select": [
      [
       { "params": [ "rx_bytes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eth_port",
     "select": [
      [
       { "params": [ "tx_bytes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node TX Data",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp",
     "select": [
      [
       { "params": [ "sent_data" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "$tag_node TX Packets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp",
     "select": [
      [
       { "params": [ "sent_packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node RX Data",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp",
     "select": [
      [
       { "params": [ "recv_packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "$tag_node RX Data",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tcp",
     "select": [
      [
       { "params": [ "bytes_acked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UDP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "udp",
     "select": [
      [
       { "params": [ "datagrams_delivered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "udp",
     "select": [
      [
       { "params": [ "recv_datagrams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "udp",
     "select": [
      [
       { "params": [ "sent_datagrams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  }
 ]
}